plugins {
    id 'java'
}

group = 'fr.mrcubee'
version = '1.0'
description = 'Vanilla plugin'

repositories {
    mavenCentral()
    maven {
        url = 'https://hub.spigotmc.org/nexus/content/groups/public/'

        content {
            includeGroup 'org.bukkit'
            includeGroup 'org.spigotmc'
        }
    }
    mavenLocal()
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly 'org.spigotmc:spigot:1.21.11-R0.1-SNAPSHOT'
}

jar {

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    exclude "**/META-INF/**"
}

ext.getGitInfo = {
    if (ext.has('gitInfoCache')) return ext.gitInfoCache

    def run = {List<String> cmd ->
        try {
            def process = new ProcessBuilder(cmd).directory(rootDir).redirectErrorStream(true).start()

            process.waitFor()
            return process.inputStream.text.trim()
        } catch (ignored) { return '' }
    }

    def commit = run(['git','rev-parse','--short=8','HEAD'])
    def dirty  = run(['git','status','--porcelain'])
    def branch = run(['git','rev-parse','--abbrev-ref','HEAD'])

    ext.gitInfoCache = [
            commit: commit ?: 'unknown',
            branch: branch ?: 'unknown',
            dirty : dirty ? '-dirty' : ''
    ]
    ext.gitInfoCache
}

processResources {
    def git = rootProject.ext.getGitInfo()

    filesMatching('plugin.yml') {
        expand(
                name: 'CubeeVanilla',
                description: project.description,
                version: "${project.version}+${git.branch}-${git.commit}${git.dirty}"
        )
    }
}