def modules = [
        "core",
        "nms"
]

modules.each {
    var moduleName = ":cubee-vanilla-${it}"

    if (it === 'nms') {
        file(it).listFiles()?.findAll { it.isDirectory() && it.name.startsWith('v')  } ?.each {
            var versionName = "${moduleName}-${it.name}"

            include versionName
            project(versionName).projectDir = file(it)
        }
    }
    include moduleName
    project(moduleName).projectDir = file(it)
}


rootProject.name = 'cubee-vanilla'